export * from "./services/auth"
export * from "./services/campus"
export * from "./services/chat"
export * from "./services/query"
export * from "./services/record"
export * from "./services/section"
export * from "./services/upload"
export * from "./services/user"